Algoritmo "Questão 05"
// Fazer um programa que pergunte o salário de um funcionário
// e apresente este salário com um aumento de 15%
Var
// Seção de Declarações das variáveis 
salario, aumento: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Qual o seu salário? ")
leia (salario)

aumento <- (salario * 15/100) + salario
escreva ("Este é seu salário com um aumento de 15%: ", aumento)
Fimalgoritmo