Algoritmo "Questão04"
// Fazer um programa que pergunte um número inteiro e apresente
// o seu antecessor e seu sucessor.
Var
// Seção de Declarações das variáveis 
Numero1, sucessor, antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Escreva um número: ")
leia (Numero1)

sucessor <- Numero1 + 1
escreval ("O sucessor é:", sucessor)

antecessor <- Numero1 - 1
escreva ("O antecessor é:", antecessor)

Fimalgoritmo